# Goldsky configuration for Plasma Network
name: lithos-subgraph
version: "1.0.0"

# Network configuration for Plasma
network:
  name: plasma-mainnet
  chain_id: 9745 # Actual Plasma testnet chain ID
  rpc_url: https://rpc.plasma.to

# Subgraph configuration
subgraph:
  schema: schema.graphql
  manifest: subgraph.yaml

# Data sources
sources:
  - name: PairFactory
    address: "0x71a870D1c935C2146b87644DF3B5316e8756aE18"
    start_block: 2204716

  - name: RouterV2
    address: "0xD70962bd7C6B3567a8c893b55a8aBC1E151759f3"
    start_block: 2204949

# Deployment settings
deployment:
  env: production
  auto_sync: true
